# Generated by Django 3.1.1 on 2020-10-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_flavour',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
