# Generated by Django 3.1.1 on 2020-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_flavour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
